<?php

namespace oxcom\phpbbch\core;

class settings
{
    /**
     * Get list of available languages
     *
     * @return array
     */
    public static function getLanguages()
    {
        $list = [
            'apache'         => ' Apache',
            'bash'           => ' Bash',
            'cs'             => ' C#',
            'cpp'            => ' C++',
            'css'            => ' CSS',
            'coffeescript'   => ' CoffeeScript',
            'diff'           => ' Diff',
            'xml'            => ' HTML, XML',
            'http'           => ' HTTP',
            'ini'            => ' Ini',
            'json'           => ' JSON',
            'java'           => ' Java',
            'javascript'     => ' JavaScript',
            'makefile'       => ' Makefile',
            'markdown'       => ' Markdown',
            'nginx'          => ' Nginx',
            'objectivec'     => ' Objective-C',
            'php'            => ' PHP',
            'perl'           => ' Perl',
            'python'         => ' Python',
            'ruby'           => ' Ruby',
            'sql'            => ' SQL',
            'shell'          => ' Shell Session',
            '1c'             => ' 1C:Enterprise (v7, v8)',
            'armasm'         => ' ARM Assembly',
            'avrasm'         => ' AVR Assembler',
            'accesslog'      => ' Access log',
            'actionscript'   => ' ActionScript',
            'ada'            => ' Ada',
            'applescript'    => ' AppleScript',
            'arduino'        => ' Arduino',
            'asciidoc'       => ' AsciiDoc',
            'aspectj'        => ' AspectJ',
            'abnf'           => ' Augmented Backus-Naur Form',
            'autohotkey'     => ' AutoHotkey',
            'autoit'         => ' AutoIt',
            'awk'            => ' Awk',
            'axapta'         => ' Axapta',
            'bnf'            => ' Backus–Naur Form',
            'basic'          => ' Basic',
            'brainfuck'      => ' Brainfuck',
            'cal'            => ' C/AL',
            'cmake'          => ' CMake',
            'csp'            => ' CSP',
            'cos'            => ' Caché Object Script',
            'capnproto'      => ' Cap’n Proto',
            'ceylon'         => ' Ceylon',
            'clean'          => ' Clean',
            'clojure'        => ' Clojure',
            'clojure-repl'   => ' Clojure REPL',
            'coq'            => ' Coq',
            'crystal'        => ' Crystal',
            'd'              => ' D',
            'dns'            => ' DNS Zone file',
            'dos'            => ' DOS .bat',
            'dart'           => ' Dart',
            'delphi'         => ' Delphi',
            'dts'            => ' Device Tree',
            'django'         => ' Django',
            'dockerfile'     => ' Dockerfile',
            'dust'           => ' Dust',
            'erb'            => ' ERB (Embedded Ruby)',
            'elixir'         => ' Elixir',
            'elm'            => ' Elm',
            'erlang'         => ' Erlang',
            'erlang-repl'    => ' Erlang REPL',
            'excel'          => ' Excel',
            'ebnf'           => ' Extended Backus-Naur Form',
            'fsharp'         => ' F#',
            'fix'            => ' FIX',
            'flix'           => ' Flix',
            'fortran'        => ' Fortran',
            'gcode'          => ' G-code (ISO 6983)',
            'gams'           => ' GAMS',
            'gauss'          => ' GAUSS',
            'glsl'           => ' GLSL',
            'gherkin'        => ' Gherkin',
            'go'             => ' Go',
            'golo'           => ' Golo',
            'gradle'         => ' Gradle',
            'groovy'         => ' Groovy',
            'hsp'            => ' HSP',
            'htmlbars'       => ' HTMLBars',
            'haml'           => ' Haml',
            'handlebars'     => ' Handlebars',
            'haskell'        => ' Haskell',
            'haxe'           => ' Haxe',
            'hy'             => ' Hy',
            'irpf90'         => ' IRPF90',
            'inform7'        => ' Inform 7',
            'x86asm'         => ' Intel x86 Assembly',
            'julia'          => ' Julia',
            'julia-repl'     => ' Julia REPL',
            'kotlin'         => ' Kotlin',
            'ldif'           => ' LDIF',
            'llvm'           => ' LLVM IR',
            'lasso'          => ' Lasso',
            'leaf'           => ' Leaf',
            'less'           => ' Less',
            'lsl'            => ' Linden Scripting Language',
            'lisp'           => ' Lisp',
            'livecodeserver' => ' LiveCode',
            'livescript'     => ' LiveScript',
            'lua'            => ' Lua',
            'mel'            => ' MEL',
            'mipsasm'        => ' MIPS Assembly',
            'mathematica'    => ' Mathematica',
            'matlab'         => ' Matlab',
            'maxima'         => ' Maxima',
            'mercury'        => ' Mercury',
            'routeros'       => ' Microtik RouterOS script',
            'mizar'          => ' Mizar',
            'mojolicious'    => ' Mojolicious',
            'monkey'         => ' Monkey',
            'moonscript'     => ' MoonScript',
            'n1ql'           => ' N1QL',
            'nsis'           => ' NSIS',
            'nimrod'         => ' Nimrod',
            'nix'            => ' Nix',
            'ocaml'          => ' OCaml',
            'openscad'       => ' OpenSCAD',
            'ruleslanguage'  => ' Oracle Rules Language',
            'oxygene'        => ' Oxygene',
            'parser3'        => ' Parser3',
            'pony'           => ' Pony',
            'powershell'     => ' PowerShell',
            'processing'     => ' Processing',
            'prolog'         => ' Prolog',
            'protobuf'       => ' Protocol Buffers',
            'puppet'         => ' Puppet',
            'purebasic'      => ' PureBASIC',
            'profile'        => ' Python profile',
            'q'              => ' Q',
            'qml'            => ' QML',
            'r'              => ' R',
            'rib'            => ' RenderMan RIB',
            'rsl'            => ' RenderMan RSL',
            'roboconf'       => ' Roboconf',
            'rust'           => ' Rust',
            'scss'           => ' SCSS',
            'sml'            => ' SML',
            'sqf'            => ' SQF',
            'step21'         => ' STEP Part 21',
            'scala'          => ' Scala',
            'scheme'         => ' Scheme',
            'scilab'         => ' Scilab',
            'smali'          => ' Smali',
            'smalltalk'      => ' Smalltalk',
            'stan'           => ' Stan',
            'stata'          => ' Stata',
            'stylus'         => ' Stylus',
            'subunit'        => ' SubUnit',
            'swift'          => ' Swift',
            'tp'             => ' TP',
            'taggerscript'   => ' Tagger Script',
            'tcl'            => ' Tcl',
            'tex'            => ' TeX',
            'tap'            => ' Test Anything Protocol',
            'thrift'         => ' Thrift',
            'twig'           => ' Twig',
            'typescript'     => ' TypeScript',
            'vbnet'          => ' VB.NET',
            'vbscript'       => ' VBScript',
            'vbscript-html'  => ' VBScript in HTML',
            'vhdl'           => ' VHDL',
            'vala'           => ' Vala',
            'verilog'        => ' Verilog',
            'vim'            => ' Vim Script',
            'xl'             => ' XL',
            'xquery'         => ' XQuery',
            'yaml'           => ' YAML',
            'zephir'         => ' Zephir',
            'crmsh'          => ' crmsh',
            'dsconfig'       => ' dsconfig',
            'jboss-cli'      => ' jboss-cli',
            'pf'             => ' pf',
        ];

        return $list;
    }

    /**
     * Get list of available themes
     *
     * @return array
     */
    public static function getThemes()
    {
        $list = [
            'default'                   => 'Default',
            'agate'                     => 'Agate',
            'androidstudio'             => 'Android Studio',
            'arduino-light'             => 'Arduino Light',
            'arta'                      => 'Arta',
            'ascetic'                   => 'Ascetic',
            'atelier-cave-dark'         => 'Atelier Cave Dark',
            'atelier-cave-light'        => 'Atelier Cave Light',
            'atelier-dune-dark'         => 'Atelier Dune Dark',
            'atelier-dune-light'        => 'Atelier Dune Light',
            'atelier-estuary-dark'      => 'Atelier Estuary Dark',
            'atelier-estuary-light'     => 'Atelier Estuary Light',
            'atelier-forest-dark'       => 'Atelier Forest Dark',
            'atelier-forest-light'      => 'Atelier Forest Light',
            'atelier-heath-dark'        => 'Atelier Heath Dark',
            'atelier-heath-light'       => 'Atelier Heath Light',
            'atelier-lakeside-dark'     => 'Atelier Lakeside Dark',
            'atelier-lakeside-light'    => 'Atelier Lakeside Light',
            'atelier-plateau-dark'      => 'Atelier Plateau Dark',
            'atelier-plateau-light'     => 'Atelier Plateau Light',
            'atelier-savanna-dark'      => 'Atelier Savanna Dark',
            'atelier-savanna-light'     => 'Atelier Savanna Light',
            'atelier-seaside-dark'      => 'Atelier Seaside Dark',
            'atelier-seaside-light'     => 'Atelier Seaside Light',
            'atelier-sulphurpool-dark'  => 'Atelier Sulphurpool Dark',
            'atelier-sulphurpool-light' => 'Atelier Sulphurpool Light',
            'atom-one-dark'             => 'Atom One Dark',
            'atom-one-light'            => 'Atom One Light',
            'brown-paper'               => 'Brown Paper',
            'codepen-embed'             => 'Codepen Embed',
            'color-brewer'              => 'Color Brewer',
            'darcula'                   => 'Darcula',
            'dark'                      => 'Dark',
            'darkula'                   => 'Darkula',
            'docco'                     => 'Docco',
            'dracula'                   => 'Dracula',
            'far'                       => 'Far',
            'foundation'                => 'Foundation',
            'github-gist'               => 'Github Gist',
            'github'                    => 'Github',
            'googlecode'                => 'Googlecode',
            'grayscale'                 => 'Grayscale',
            'gruvbox-dark'              => 'Gruvbox Dark',
            'gruvbox-light'             => 'Gruvbox Light',
            'hopscotch'                 => 'Hopscotch',
            'hybrid'                    => 'Hybrid',
            'idea'                      => 'Idea',
            'ir-black'                  => 'Ir Black',
            'kimbie.dark'               => 'Kimbie Dark',
            'kimbie.light'              => 'Kimbie Light',
            'magula'                    => 'Magula',
            'mono-blue'                 => 'Mono Blue',
            'monokai-sublime'           => 'Monokai Sublime',
            'monokai'                   => 'Monokai',
            'obsidian'                  => 'Obsidian',
            'ocean'                     => 'Ocean',
            'paraiso-dark'              => 'Paraiso Dark',
            'paraiso-light'             => 'Paraiso Light',
            'pojoaque'                  => 'Pojoaque',
            'purebasic'                 => 'Purebasic',
            'qtcreator_dark'            => 'Qtcreator Dark',
            'qtcreator_light'           => 'Qtcreator Light',
            'railscasts'                => 'Railscasts',
            'rainbow'                   => 'Rainbow',
            'routeros'                  => 'Routeros',
            'school-book'               => 'School Book',
            'solarized-dark'            => 'Solarized Dark',
            'solarized-light'           => 'Solarized Light',
            'sunburst'                  => 'Sunburst',
            'tomorrow-night-blue'       => 'Tomorrow Night Blue',
            'tomorrow-night-bright'     => 'Tomorrow Night Bright',
            'tomorrow-night-eighties'   => 'Tomorrow Night Eighties',
            'tomorrow-night'            => 'Tomorrow Night',
            'tomorrow'                  => 'Tomorrow',
            'vs'                        => 'Vs',
            'vs2015'                    => 'Vs 2015',
            'xcode'                     => 'Xcode',
            'xt256'                     => 'Xt 256',
            'zenburn'                   => 'Zenburn',
        ];

        return $list;
    }
}
